menu:
  Home:
  Archives: archives

widgets:
- category
- tag

excerpt_link: Read More

twitter:
  username: Nennad
  show_replies: true
  tweet_count: 5

addthis:
  enable: false


fancybox: true

google_analytics: "UA-51730089-1"
rss:


