# head
menu:
  Home: /
#  Archives: /archives
rss: /atom.xml
favicon: /favicon.png

# main
date_format: 'MMMM D, YYYY'
excerpt_link: READ MORE
comment_link: 0 COMMENTS
comments_enabled: false
# foot
# themes_mata: ' ❤ Theme by <a href="http://unmric.com" target="_blank">unmric</a>'
google_analytics:
